# Redirect all API requests to the Render backend. 
[[redirects]]
  from = "/api/*"
  to = "https://bangladesh-top-1-esports.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  CI = "false"

